Abort start script if error occurred during build

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -52,8 +52,14 @@ fi
 echo
 echo '⚓️  Composing'
 echo '—————————————————————————————————————————————'
-docker-compose up -d
-
-./bin/haproxy-start
+if ! docker-compose up -d; then
+	echo
+	echo '—————————————————————————————————————————————'
+	echo '🚨 Error composing: aborting'
+	echo '—————————————————————————————————————————————'
+	exit 1
+fi
 
 unset response
+
+bin/haproxy-start
